### ISSUE TITLE
Error During WET dry classification for new data

### ISSUE THREAD

**Issue by GayanSandaruwan** [overeem11/RAINLINK#6]
I encountered the following error while trying to run the data from a region in my country. PreprocessingMinMaxRSL successfully completes and the WetDryNearbyLinkApMinMaxRSL gives the following error.`Error in `$<-.data.frame`(`*tmp*`, "ID", value = character(0)) : 
  replacement has 0 rows, data has 317626` .
Any help would be a lot.

**Comment by GayanSandaruwan** [comment]
BTW sample data runs without any problems, and I should mention that I'm not much practiced with R language, So, the problem might not be with package. But, I used the exact same Run.R script just changing the `data(linkdata)` to `data('srilanka')` and data attribute in `PreprocessingMinMaxRSL` to srilanka. Rest is same.

**Comment by giacom0rovers1** [comment]
Hi @GayanSandaruwan ! 
I would suggest to open the issue on your forked version. So it will be easier to reproduce and hopefully solve. Thanks

**Comment by giacom0rovers1** [comment]
Sorry I just noticed that forked repos have no issues! I will download your version and try to reproduce.

**Comment by giacom0rovers1** [comment]
I can not reproduce the error with the information provided and using your forked version. You should upload your sample data set 'srilanka', as it seems like a problem related to the way the data set is formatted. I have worked a lot on data preparation to use the algorithm on my italian region. I will hopefully upload something of what I have done in the next months. 

I take this opportunity to report also that **the Run.R script is not ready for a "source()" call**. 
The modified function calls to use without the WetDry classification do overwrite the already computed variables. You should either specify this in the "how_to_install.md" guide, point 9. or comment the lines in the Run.R script. I have modified the Run.R file with some if's and a boolean variable which controls the WetDry on-off choice.

**Comment by GayanSandaruwan** [comment]
Hi @giacom0rovers1  sorry for the late, had to wait to get permission to share the data. I've added a sample data file in the data/sriLanka.RData in th branch **SL***

**Comment by GayanSandaruwan** [comment]
@giacom0rovers1 Sorry for the late, I had to get permission to share the data. I've add the Data file in the data/sriLanka.RData in ``SL`` branch. And try the Run-SL.R to reproduce the error. BTW thanks a lot for support.

**Comment by GayanSandaruwan** [comment]
> I take this opportunity to report also that the Run.R script is not ready for a "source()" call.
The modified function calls to use without the WetDry classification do overwrite the already computed variables. 

Yes there is something with the variable name "**linkdata**" I suspect this is caused by the the RAINLINK_1.11 package. As the package contains the linkdata.RData file in it's data/ directory though we add some other data file with same name the one in the library gets loaded to the environment. 

> You should either specify this in the "how_to_install.md" guide, point 9. or comment the lines in the Run.R script. I have modified the Run.R file with some if's and a boolean variable which controls the WetDry on-off choice.

How else should this be good to call. :face_with_head_bandage:

**Comment by giacom0rovers1** [comment]
Ok I have found the bug :sunglasses: 
It is just that the first column is named "Id" instead of "ID" which is the name required (R is case sensitive). Just add this line after calling data("srilanka"): 

`colnames(x)[1] <- "ID"`

I have now another error: (sorry for some parts in italian)
```
Error in ind_PrevPeriod[i]:i : 
  il risultato sarebbe un vettore troppo lungo
Inoltre: Warning message:
In min(which(t_sec[ind_PrevPeriod[i - 1]:(i - 1)] > (t_sec[i] -  :
  no non-missing arguments to min; returning Inf
```
For what I can see, this is related to the DateTime column, which is formatted badly. You should have character strings in the format "YYYYmmddHHMM" (UTC timezone) instead of numeric values (i.e. 9.97040184669283e-313).

**Comment by GayanSandaruwan** [comment]
Oh, How could I not see that :man_facepalming:  Thanks a lot @giacom0rovers1 . I fixed the DateTime format issue as well. But, now there is something else.
```if(!dir.exists(FolderRainEstimates)){ dir.create(FolderRainEstimates) }
  ID <- unique(DataPreprocessed$ID)
  t <- sort(unique(DataPreprocessed$DateTime))
  t_sec <- as.numeric(as.POSIXct(as.character(t), format = "%Y%m%d%H%M"))
  dt <- min(diff(t_sec))
  for (i in 1 : length(t))
  {
    ind <- which(DataPreprocessed$DateTime == t[i])
    int_data <- data.frame(ID = DataPreprocessed$ID[ind], RainfallDepthPath = Rmean[ind] * dt / 3600, 
                           PathLength = DataPreprocessed$PathLength[ind], XStart = DataPreprocessed$XStart[ind], 
                           YStart = DataPreprocessed$YStart[ind], XEnd = DataPreprocessed$XEnd[ind], 
                           YEnd = DataPreprocessed$YEnd[ind], IntervalNumber = rep(i, length(ind)), 
                           Frequency = DataPreprocessed$Frequency[ind])
    Filename <- paste(FolderRainEstimates, "/linkdata_", t[i], ".dat", sep="")
    write.table(int_data, Filename, row.names = FALSE, col.names = TRUE, append = FALSE, quote = FALSE)
  }
}
```

**Above code line number 162 in Run-SL.r gives the following error** 

``Error in data.frame(ID = DataPreprocessed$ID[ind], RainfallDepthPath = Rmean[ind] *  : 
  arguments imply differing number of rows: 3310, 0``

**Comment by GayanSandaruwan** [comment]
Data with updated column name and type is pushed to the repo.

**Comment by GayanSandaruwan** [comment]
Would it lead to an error if  two rows are added for the same link i.e. A to B as one raw and B to A as another raw ?

**Comment by giacom0rovers1** [comment]
> Would it lead to an error if two rows are added for the same link i.e. A to B as one raw and B to A as another raw ?

I would say no, if they have different IDs as expected from the algorithm. You need also to switch Start and End coordinates in order to let the algorithm know that you are referring to the other direction.

**Comment by giacom0rovers1** [comment]
> Above code line number 162 in Run-SL.r gives the following error
Error in data.frame(ID = DataPreprocessed$ID[ind], RainfallDepthPath = Rmean[ind] * : arguments imply differing number of rows: 3310, 0

Again you have a wrong column name. It's XStart not Xstart :yum: 

I can see also that all your Pmax values are all +15 dBm so I presume they are the transmitted powers.
You have then to follow these instructions to compute the negative attenuations along the path before processing them with the algorithm.

From ManualRAINLINK.pdf : 

> In case of a sampling strategy providing instantaneous values of received and transmitted
power levels, the following steps need to be undertaken to use RAINLINK:

> 1. Compute the attenuation over the link path by subtracting the transmitted power
from the received power. The actual attenuation is the transmitted minus the received
power. Hence, the computed attenuation is the actual attenuation multiplied with mi-
nus one, i.e. a negative attenuation. This is needed for RAINLINK in order to work
properly. Do this for every link and time interval. Note that the computed attenuation
includes all sources of attenuation along the link path, e.g. wet antenna attenuation,
free space losses, and rain-induced attenuation.

> 2. Replace the two columns with minimum and maximum received power, respectively
P min and P max in dBm, in the input data with the computed attenuation from the previ-
ous step. This implies that the columns with the header names P min and P max become
identical.

> 3. Use the altered input data in RAINLINK.

So:
```
colnames(x) <- c("ID", "Pmax","Pmin","XStart","YStart","XEnd","YEnd","DateTime","PathLength","Frequency")
negAttenuation <- x$Pmin - x$Pmax
x$Pmin <- x$Pmax <- negAttenuation

```

I try to push the modifications directly to the Run_SL.R code.

**Comment by giacom0rovers1** [comment]
Now it works without errors but it sees no rain at all. 

To go after point 6. you need to add an interpolation grid of your region and to specify your location in the file Config.R in the _Google Maps: Specific Settings_ section.

**Comment by overeem11** [comment]
RAINLINK also works with so called full-duplex data, i.e. link data from two directions over the same link path. A full-duplex link should indeed have two IDs, one for each link direction. I also used switched Start and End coordinates, but I think this is not necessary. By the way, I expect that the telecommunication company will usually provide switched Start and End coordinates.

Van: Giacomo Roversi [mailto:notifications@github.com]
Verzonden: donderdag 7 juni 2018 13:06
Aan: overeem11/RAINLINK
CC: Subscribed
Onderwerp: Re: [overeem11/RAINLINK] Error During WET dry classification for new data (#6)


Would it lead to an error if two rows are added for the same link i.e. A to B as one raw and B to A as another raw ?

I would say no, if they have different IDs as expected from the algorithm. You need also to switch Start and End coordinates in order to let the algorithm know that you are referring to the other direction.

**Comment by overeem11** [comment]
It will indeed overwrite already computed variables in the wet-dry classification when “source()” call is used. Users can make their own “Run.R” file and remove processing steps which are not relevant for them.

If you lead your link data after the line with “data(Linkdata)” I expect that it will work. Alternatively, the “Data=Linkdata” statements in “Run.R” could be replaced by e.g. “Data=OwnData”, where OwnData contains your own microwave link data, which could be read by e.g. “read.table”.

Van: GayanSandaruwan [mailto:notifications@github.com]
Verzonden: woensdag 6 juni 2018 19:10
Aan: overeem11/RAINLINK
CC: Subscribed
Onderwerp: Re: [overeem11/RAINLINK] Error During WET dry classification for new data (#6)


I take this opportunity to report also that the Run.R script is not ready for a "source()" call.
The modified function calls to use without the WetDry classification do overwrite the already computed variables.

Yes there is something with the variable name "linkdata" I suspect this is caused by the the RAINLINK_1.11 package. As the package contains the linkdata.RData file in it's data/ directory though we add some other data file with same name the one in the library gets loaded to the environment.

You should either specify this in the "how_to_install.md" guide, point 9. or comment the lines in the Run.R script. I have modified the Run.R file with some if's and a boolean variable which controls the WetDry on-off choice.
How else should this be good to call. 🤕

**Comment by GayanSandaruwan** [comment]
:nerd_face:  Thanks a lot @giacom0rovers1. Can't think of a way to thank you. 

> Now it works without errors but it sees no rain at all.

Yes, During that day there have not much of rainfall been reported.
I'll run the package with more dates and will inform you.

**Comment by GayanSandaruwan** [comment]
@overeem11  Thanks for the info. 

I've one more question. **a**,**b** you have used are only depending on the frequency. But according to the literature this should depend on the temperature as well, are there any measures you have used to reduce the effect or the effect from temperature is insignificant ?

**Comment by overeem11** [comment]
The coefficients a & b are mainly dependent on microwave frequency, and to some extent also on polarisation, temperature, drop shape, and canting angle distribution (this has not been taken into account). So it could be that for warm climates, such as encountered in Sri Lanka, other values are more optimal, but microwave frequency is the most important. Temperature was found to be of minor influence for links with frequencies above 10 GHz (Leijnse, H., cited 2007: Hydrometeorological application of microwave links: Measurement of evaporation and precipitation. Ph.D. thesis, Wageningen University, 134 pp. [Available online at http://library.wur.nl/wda/dissertations/dis4353.pdf.]).

So you could search for literature describing values of a & b for temperatures being representative of the Sri Lanka climate, but the effect is generally small. Leijnse et al. (2007; doi:10.1029/2006WR004989) confirms the weak dependence on temperature, and provides a Table (nr. 1) with values for a & b in the k-R relationship (i.e. not the R-k!) for different drop size distributions and temperatures.


Van: GayanSandaruwan [mailto:notifications@github.com]
Verzonden: donderdag 7 juni 2018 15:47
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Mention
Onderwerp: Re: [overeem11/RAINLINK] Error During WET dry classification for new data (#6)


@overeem11<https://github.com/overeem11> Thanks for the info.

I've one more question. a,b you have used are only depending on the frequency. But according to the literature this should depend on the temperature as well, are there any measures you have used to reduce the effect or the effect from temperature is insignificant ?

**Comment by GayanSandaruwan** [comment]
We are having bit of a trouble finding these a,b, distributions. So far we could omly find the distributions for -10°C ,0,20 only. If you know some resource on that would be much of a help.

**Comment by GayanSandaruwan** [comment]
Can not access the link given to the Phd thesis. Maybe due to a access restriction, I'll try it with university wifi connection later 😊

**Comment by overeem11** [comment]
Many publications just use the ITU values (ITU-R P.838-3). Please have a look at Table 1 in Leijnse et al. (2007; doi:10.1029/2006WR004989). There is some information for a 7 GHz link in West Africa in doi:10.1002/2014GL060724. There will be more, but generally quite hard to find for a specific climate.

Van: GayanSandaruwan [mailto:notifications@github.com]
Verzonden: donderdag 7 juni 2018 16:44
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Mention
Onderwerp: Re: [overeem11/RAINLINK] Error During WET dry classification for new data (#6)


We are having bit of a trouble finding these a,b, distributions. So far we could omly find the distributions for -10°C ,0,20 only. If you know some resource on that would be much of a help.

**Comment by overeem11** [comment]
This should work: http://www.hydrology.nl/images/docs/dutch/2007.12.21_Hidde_Leijnse.pdf


Van: GayanSandaruwan [mailto:notifications@github.com]
Verzonden: donderdag 7 juni 2018 16:51
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Mention
Onderwerp: Re: [overeem11/RAINLINK] Error During WET dry classification for new data (#6)


Can not access the link given to the Phd thesis. Maybe due to a access restriction, I'll try it with university wifi connection later 😊

**Comment by GayanSandaruwan** [comment]
Yes, thad did. Thanks again for the support. I'll close this issue as it is deviating from the    topic of the issue. Can I have your email adress or is it okay to discuss any question through a git hub issue 🤔

**Comment by overeem11** [comment]
As far as I’m concerned it is indeed more convenient to discuss these type of issues via mail (overeem@knmi.nl).

Van: GayanSandaruwan [mailto:notifications@github.com]
Verzonden: donderdag 7 juni 2018 17:06
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Mention
Onderwerp: Re: [overeem11/RAINLINK] Error During WET dry classification for new data (#6)


Yes, thad did. Thanks again for the support. I'll close this issue as it is deviating from the topic of the issue. Can I have your email adress or is it okay to discuss any question through a git hub issue 🤔

**Comment by GayanSandaruwan** [comment]
Thank you !
